
  



DCF_MULTI_STAGE_FCF_FUNC <- function(CURRENT_REVENUE, CURRENT_CAPITAL_SPENDING,
                                     CURRENT_DEPRECIATION, TAX_RATE_INCOME,
                                     BOOK_VALUE_DEBT, BOOK_VALUE_EQUITY,
                                     NOL_CARRIED_FORWARD, PUBLICLY_TRADED_FLAG,
                                     LAST_TRADED_PRICE, NUMBER_SHARES_OUTSTANDING,
                                     MARKET_VALUE_DEBT, DEBT_CAPITAL_RATIO,
                                     COST_EQUITY, BETA_STOCK,
                                     RISK_FREE_RATE, RISK_PREMIUM,
                                     COST_DEBT, GROWTH_RATE_STABLE_PERIOD,
                                     OPERATING_EXPENSE_STABLE_PERIOD, WORKING_CAPITAL_STABLE_PERIOD,
                                     BETA_STABLE_PERIOD, DEBT_RATIO_STABLE_PERIOD,
                                     COST_DEBT_FLAG, COST_DEBT_STABLE_PERIOD,
                                     CAPITAL_EXPENDITURES_STABLE_PERIOD, GROWTH_RATE_REVENUE_RNG,
                                     OPERATING_EXPENSE_RNG, GROWTH_RATE_CAPITAL_SPENDING_RNG,
                                     GROWTH_RATE_DEPRECIATION_RNG, WORKING_CAPITAL_RNG, EXCESS_RETURN_PERIODS = 10,
                                     CAP_PERIODS = 5, OUTPUT = 0) {

  GROWTH_RATE_REVENUE_VECTOR <- GROWTH_RATE_REVENUE_RNG
  OPERATING_EXPENSE_VECTOR <- OPERATING_EXPENSE_RNG
  GROWTH_RATE_CAPITAL_SPENDING_VECTOR <- GROWTH_RATE_CAPITAL_SPENDING_RNG
  GROWTH_RATE_DEPRECIATION_VECTOR <- GROWTH_RATE_DEPRECIATION_RNG
  WORKING_CAPITAL_VECTOR <- WORKING_CAPITAL_RNG
  

  if(nrow(GROWTH_RATE_REVENUE_RNG) == 1)                                  {    GROWTH_RATE_REVENUE_VECTOR <- t(GROWTH_RATE_REVENUE_RNG)  }
  if(nrow(GROWTH_RATE_REVENUE_VECTOR) != EXCESS_RETURN_PERIODS)           {    stop("Number of columns not equal to EXCESS_RETURN_PERIODS")  }
  
  if(nrow(OPERATING_EXPENSE_RNG) == 1)                                    {    OPERATING_EXPENSE_VECTOR <- t(OPERATING_EXPENSE_RNG)  }
  if(nrow(OPERATING_EXPENSE_VECTOR) != EXCESS_RETURN_PERIODS)             {    stop("Number of columns not equal to EXCESS_RETURN_PERIODS")  }
  
  if(nrow(GROWTH_RATE_CAPITAL_SPENDING_RNG) == 1)                         {    GROWTH_RATE_CAPITAL_SPENDING_VECTOR <- t(GROWTH_RATE_CAPITAL_SPENDING_RNG)  }
  if(nrow(GROWTH_RATE_CAPITAL_SPENDING_VECTOR) != EXCESS_RETURN_PERIODS)  {    stop("Number of columns not equal to EXCESS_RETURN_PERIODS")  }
  
  if(nrow(GROWTH_RATE_DEPRECIATION_RNG) == 1)                             {    GROWTH_RATE_DEPRECIATION_VECTOR <- t(GROWTH_RATE_DEPRECIATION_RNG)  }
  if(nrow(GROWTH_RATE_DEPRECIATION_VECTOR) != EXCESS_RETURN_PERIODS)      {    stop("Number of columns not equal to EXCESS_RETURN_PERIODS")  }
  
  if(nrow(WORKING_CAPITAL_RNG) == 1)                                      {    WORKING_CAPITAL_VECTOR <- t(WORKING_CAPITAL_RNG)  }
  if(nrow(WORKING_CAPITAL_VECTOR) != EXCESS_RETURN_PERIODS)               {    stop("Number of columns not equal to EXCESS_RETURN_PERIODS")  }

  
  
  TEMP_MATRIX <- matrix(, nrow = 33, ncol = EXCESS_RETURN_PERIODS + 1)
  
  COST_EQUITY_VAL <- ifelse(COST_EQUITY != 0, COST_EQUITY, RISK_FREE_RATE + BETA_STOCK * RISK_PREMIUM)
  EQUITY_DEBT_RATIO <- ifelse(PUBLICLY_TRADED_FLAG == TRUE, LAST_TRADED_PRICE * NUMBER_SHARES_OUTSTANDING / (MARKET_VALUE_DEBT + LAST_TRADED_PRICE * NUMBER_SHARES_OUTSTANDING), 
                              ifelse(DEBT_CAPITAL_RATIO = 0, 1 - BOOK_VALUE_DEBT / (BOOK_VALUE_DEBT + BOOK_VALUE_EQUITY), 1 - DEBT_CAPITAL_RATIO))
  AFTER_TAX_COST_DEBT <- COST_DEBT * (1 - TAX_RATE_INCOME)
  DEBT_CAPITAL_VAL <- 1 - EQUITY_DEBT_RATIO
  COST_CAPITAL_VAL <- COST_EQUITY_VAL * EQUITY_DEBT_RATIO + AFTER_TAX_COST_DEBT * DEBT_CAPITAL_VAL
  
  for(j in 1:EXCESS_RETURN_PERIODS) {

    TEMP_MATRIX[1,j] <- j
    
    ifelse(j > 1, TEMP_MATRIX[2,j] <- TEMP_MATRIX[2,j-1], TEMP_MATRIX[2,j] <- CURRENT_REVENUE * (1 + GROWTH_RATE_REVENUE_VECTOR[j,1]))

    TEMP_MATRIX[3,j] <- TEMP_MATRIX[2,j] * OPERATING_EXPENSE_VECTOR[j,1]
    TEMP_MATRIX[4,j] <- TEMP_MATRIX[2,j] - TEMP_MATRIX[3,j]
    
    if(j > 1) {
      TEMP_MATRIX[5,j] <- ifelse(TEMP_MATRIX[4,j] > 0, ifelse(TEMP_MATRIX[12,j-1] > TEMP_MATRIX[4,j], 0, (TEMP_MATRIX[4,j] - TEMP_MATRIX[12,j-1])) * TAX_RATE_INCOME, 0)
      TEMP_MATRIX[7,j] <- TEMP_MATRIX[7,j-1] * (1 + GROWTH_RATE_DEPRECIATION_VECTOR[j,1])
      TEMP_MATRIX[8,j] <- TEMP_MATRIX[8,j-1] * (1 + GROWTH_RATE_CAPITAL_SPENDING_VECTOR[j,1])
      TEMP_MATRIX[9,j] <- (TEMP_MATRIX[2,j] - TEMP_MATRIX [2,j-1]) * WORKING_CAPITAL_VECTOR[j,1]
      TEMP_MATRIX[12,j] <- ifelse(TEMP_MATRIX[12,j-1] > TEMP_MATRIX[4,j], TEMP_MATRIX[12,j-1] - TEMP_MATRIX[4,j], 0)
    }
    else {
      TEMP_MATRIX[5,j] <- ifelse(TEMP_MATRIX[4,j] > 0, ifelse(NOL_CARRIED_FORWARD > TEMP_MATRIX[4,j], 0, (TEMP_MATRIX[4,j] - NOL_CARRIED_FORWARD) * TAX_RATE_INCOME), 0)
      TEMP_MATRIX[7,j] <- CURRENT_DEPRECIATION * (1 + GROWTH_RATE_DEPRECIATION_VECTOR[j,1])
      TEMP_MATRIX[8,j] <- CURRENT_CAPITAL_SPENDING * (1 + GROWTH_RATE_CAPITAL_SPENDING_VECTOR[j,1])
      TEMP_MATRIX[9,j] <- (TEMP_MATRIX[2,j] - CURRENT_REVENUE) * WORKING_CAPITAL_VECTOR[j,1]
      TEMP_MATRIX[12,j] <- ifelse(NOL_CARRIED_FORWARD > 0, ifelse(NOL_CARRIED_FORWARD < TEMP_MATRIX[2,j], 0, NOL_CARRIED_FORWARD - TEMP_MATRIX[2,j]), 0)
    }
    
    TEMP_MATRIX[6,j] <- TEMP_MATRIX[4,j] - TEMP_MATRIX[5,j]
    TEMP_MATRIX[10,j] <- TEMP_MATRIX[6,j] + TEMP_MATRIX[7,j] + TEMP_MATRIX[8,j] - TEMP_MATRIX[9,j]
    TEMP_MATRIX[13,j] <- TEMP_MATRIX[5,j] / TEMP_MATRIX[4,j]
    
    if(j <= CAP_PERIODS) {
      TEMP_MATRIX[14,j] <- BETA_STOCK
      TEMP_MATRIX[17,j] <- DEBT_CAPITAL_VAL
    }
    else {
      TEMP_MATRIX[14,j] <- ifelse(BETA_STABLE_PERIOD != 0, TEMP_MATRIX[14,CAP_PERIODS] - ((TEMP_MATRIX[14,CAP_PERIODS] - BETA_STABLE_PERIOD) / CAP_PERIODS) * (j - CAP_PERIODS), BETA_STOCK)
      TEMP_MATRIX[17,j] <- ifelse(DEBT_RATIO_STABLE_PERIOD != 0, TEMP_MATRIX[17,CAP_PERIODS] - ((TEMP_MATRIX[17,CAP_PERIODS] - DEBT_CAPITAL_VAL) / CAP_PERIODS) * (j - CAP_PERIODS), DEBT_CAPITAL_VAL)
    }
    
    TEMP_MATRIX[15,j] <- ifelse(COST_EQUITY == 0, RISK_FREE_RATE + TEMP_MATRIX[14,j] * RISK_PREMIUM, COST_EQUITY)
    TEMP_MATRIX[16,j] <- COST_DEBT_STABLE_PERIOD * (1 - TAX_RATE_INCOME)
    TEMP_MATRIX[18,j] <- TEMP_MATRIX[15,j] * (1 - TEMP_MATRIX[17,j]) + TEMP_MATRIX[16,j] * TEMP_MATRIX[17,j]
    ifelse(j > 1, TEMP_MATRIX[19,j] <- TEMP_MATRIX[19,j-1] * (1 + TEMP_MATRIX[18,j]), TEMP_MATRIX[19,j] <- 1 + TEMP_MATRIX[18,j])
    TEMP_MATRIX[11,j] <- TEMP_MATRIX[10,j] / TEMP_MATRIX[19,j]
    ifelse(is.na(TEMP_MATRIX[28,1]), TEMP_MATRIX[28,1] <- TEMP_MATRIX[11,j], TEMP_MATRIX[28,1] <- TEMP_MATRIX[28,1] + TEMP_MATRIX[11,j])
  }
  
  
  
  #TEMP_MATRIX[1,EXCESS_RETURN_PERIODS+1] <- "TN"
  TEMP_MATRIX[2,EXCESS_RETURN_PERIODS+1] <- TEMP_MATRIX[2,EXCESS_RETURN_PERIODS] * (1+ GROWTH_RATE_STABLE_PERIOD)
  TEMP_MATRIX[3,EXCESS_RETURN_PERIODS+1] <- TEMP_MATRIX[2,EXCESS_RETURN_PERIODS+1] * OPERATING_EXPENSE_STABLE_PERIOD
  TEMP_MATRIX[4,EXCESS_RETURN_PERIODS+1] <- TEMP_MATRIX[2,EXCESS_RETURN_PERIODS+1] - TEMP_MATRIX[3,EXCESS_RETURN_PERIODS+1]
  TEMP_MATRIX[5,EXCESS_RETURN_PERIODS+1] <- ifelse(TEMP_MATRIX[4,EXCESS_RETURN_PERIODS+1] > 0, ifelse(TEMP_MATRIX[12,EXCESS_RETURN_PERIODS] > TEMP_MATRIX[4,EXCESS_RETURN_PERIODS+1], 0, (TEMP_MATRIX[4,EXCESS_RETURN_PERIODS+1] - TEMP_MATRIX[12,EXCESS_RETURN_PERIODS]) * TAX_RATE_INCOME), 0)
  TEMP_MATRIX[6,EXCESS_RETURN_PERIODS+1] <- TEMP_MATRIX[4,EXCESS_RETURN_PERIODS+1] - TEMP_MATRIX[5,EXCESS_RETURN_PERIODS+1]
  TEMP_MATRIX[7,EXCESS_RETURN_PERIODS+1] <- TEMP_MATRIX[7,EXCESS_RETURN_PERIODS]
  TEMP_MATRIX[8,EXCESS_RETURN_PERIODS+1] <- ifelse(CAPITAL_EXPENDITURES_STABLE_PERIOD == 0, TEMP_MATRIX[7,EXCESS_RETURN_PERIODS+1], TEMP_MATRIX[7,EXCESS_RETURN_PERIODS+1] * CAPITAL_EXPENDITURES_STABLE_PERIOD)
  TEMP_MATRIX[9,EXCESS_RETURN_PERIODS+1] <- (TEMP_MATRIX[2,EXCESS_RETURN_PERIODS+1] - TEMP_MATRIX[2,EXCESS_RETURN_PERIODS]) * WORKING_CAPITAL_STABLE_PERIOD
  TEMP_MATRIX[10,EXCESS_RETURN_PERIODS+1] <- TEMP_MATRIX[6,EXCESS_RETURN_PERIODS+1] + TEMP_MATRIX[7,EXCESS_RETURN_PERIODS+1] - TEMP_MATRIX[8,EXCESS_RETURN_PERIODS+1] - TEMP_MATRIX[9,EXCESS_RETURN_PERIODS+1]
  TEMP_MATRIX[13,EXCESS_RETURN_PERIODS+1] <- TEMP_MATRIX[5,EXCESS_RETURN_PERIODS+1] / TEMP_MATRIX[4,EXCESS_RETURN_PERIODS+1]
  TEMP_MATRIX[14,EXCESS_RETURN_PERIODS+1] <- TEMP_MATRIX[14,EXCESS_RETURN_PERIODS]
  TEMP_MATRIX[15,EXCESS_RETURN_PERIODS+1] <- ifelse(COST_EQUITY == 0, RISK_FREE_RATE + TEMP_MATRIX[14,EXCESS_RETURN_PERIODS+1] * RISK_PREMIUM, COST_EQUITY)
  TEMP_MATRIX[16,EXCESS_RETURN_PERIODS+1] <- TEMP_MATRIX[16,EXCESS_RETURN_PERIODS]
  TEMP_MATRIX[17,EXCESS_RETURN_PERIODS+1] <- TEMP_MATRIX[17,EXCESS_RETURN_PERIODS]
  TEMP_MATRIX[18,EXCESS_RETURN_PERIODS+1] <- TEMP_MATRIX[15,EXCESS_RETURN_PERIODS+1] * (1 - TEMP_MATRIX[17,EXCESS_RETURN_PERIODS+1]) + TEMP_MATRIX[16,EXCESS_RETURN_PERIODS+1] * TEMP_MATRIX[17,EXCESS_RETURN_PERIODS+1]
  TEMP_MATRIX[20,1] <- GROWTH_RATE_STABLE_PERIOD
  TEMP_MATRIX[21,1] <-TEMP_MATRIX[10,EXCESS_RETURN_PERIODS+1]
  TEMP_MATRIX[22,1] <- ifelse(BETA_STABLE_PERIOD == 0, RISK_FREE_RATE + BETA_STOCK * RISK_PREMIUM, RISK_FREE_RATE + BETA_STABLE_PERIOD * RISK_PREMIUM)
  TEMP_MATRIX[23,1] <- ifelse(DEBT_RATIO_STABLE_PERIOD != 0, 1 - DEBT_RATIO_STABLE_PERIOD, EQUITY_DEBT_RATIO)
  TEMP_MATRIX[24,1] <- ifelse(COST_DEBT_FLAG == TRUE, COST_DEBT_STABLE_PERIOD * (1 - TAX_RATE_INCOME), AFTER_TAX_COST_DEBT)
  TEMP_MATRIX[25,1] <- 1 - TEMP_MATRIX[23,1]
  TEMP_MATRIX[26,1] <- TEMP_MATRIX[22,1] * TEMP_MATRIX[23,1] + TEMP_MATRIX[24,1] * TEMP_MATRIX[25,1]
  TEMP_MATRIX[27,1] <- TEMP_MATRIX[21,1] / (TEMP_MATRIX[26,1] - TEMP_MATRIX[20,1])
  TEMP_MATRIX[29,1] <- TEMP_MATRIX[27,1] / TEMP_MATRIX[19,EXCESS_RETURN_PERIODS]
  TEMP_MATRIX[30,1] <- TEMP_MATRIX[28,1] + TEMP_MATRIX[29,1]
  TEMP_MATRIX[31,1] <- ifelse(PUBLICLY_TRADED_FLAG == TRUE, MARKET_VALUE_DEBT, BOOK_VALUE_DEBT)
  TEMP_MATRIX[32,1] <- TEMP_MATRIX[30,1] - TEMP_MATRIX[31,1]
  TEMP_MATRIX[33,1] <- TEMP_MATRIX[32,1] / NUMBER_SHARES_OUTSTANDING
  
  INTRINSIC_VALUE_SHARE <- TEMP_MATRIX[33,1]
  
  
  if(OUTPUT == 0) {
    return(INTRINSIC_VALUE_SHARE)
  }
  else if(OUTPUT == 1) {
    return(TEMP_MATRIX)
  }
}

test <- matrix(c(1:10), nrow = 10, ncol = 1)

#Function call with 2 parameters per line to match the structure of the VBA function (makes it marginally more readable)
DCF_MULTI_STAGE_FCF_FUNC(123456, 7890,
                         1234, 0.567890,
                         0.08, 7890,
                         123456, TRUE,
                         1234, 5678,
                         0.09, 0,
                         0.1, 1,
                         0.02, 0.05,
                         0.03, 0.03,
                         0.8, 0.01,
                         1, 0.15,
                         TRUE, 0.08,
                         1.1, matrix(c(rep(0.06,6),rep(0.04,4)),nrow = 1),
                         matrix(c(rep(0.8,10)), ncol = 1), matrix(c(rep(0.06,4),rep(0.04,6)), nrow = 1),
                         matrix(c(rep(0.06,5),rep(0.03,5)), nrow = 1), matrix(c(rep(0.05,10)), nrow = 1), 
                         10,5,
                         0   #important: OUTPUT parameter; change to 1 to return only the entire TEMP_MATRIX
)
